### ISSUE TITLE
Rendering issue with black color on game objects

### ISSUE THREAD

**Issue by ghost** [cxong/cdogs-sdl#646]
That kind of looks like some color key issue.
![grafik](https://user-images.githubusercontent.com/12168893/83966664-af341c00-a8bb-11ea-8409-06f2c48128dd.png)

**Comment by cxong** [comment]
Not sure what version you're running, but this should be fixed in the next release at least
![image](https://user-images.githubusercontent.com/1083215/85710450-9d5ecf80-b729-11ea-909a-c129a84784c3.png)

**Comment by chack05** [comment]
@cxong Thanks. Yeah, I should have probably written it appeared in the latest Windows binary.

**Comment by chack05** [comment]
Unfortunately, the issue still exists in 0.9. Tested in Sand.

**Comment by chack05** [comment]
@cxong Not sure if this popped up without the name tag.

**Comment by cxong** [comment]
I haven't been able to reproduce it under Windows. Could you please show me a screenshot so I know which sprite is affected, and also are you using linux?

**Comment by chack05** [comment]
@cxong 
The same terminal sprite.
![terminal](https://user-images.githubusercontent.com/12168893/94869661-1155f580-0446-11eb-97be-8b40f7a62c0f.png)
This happens both on my Windows and my Ubuntu computer, which have different GPUs.

BTW: What happened to limited ammo and ammo pickups? I can't seem to find an option to enable them...

**Comment by chack05** [comment]
@cxong Additional information:

* This happens in the editor as well.
* Another weird effect: table_plastic is drawn yellowish bright.
![table_plastic](https://user-images.githubusercontent.com/12168893/94995538-4d509e00-059f-11eb-9855-cb31c8ff6ed9.png)

**Comment by cxong** [comment]
This is really odd because I cannot reproduce it myself on windows
![image](https://user-images.githubusercontent.com/1083215/96437472-f4952c80-1251-11eb-94fa-57157208d1a3.png)
The problem is unrelated to graphics cards; the most likely problem is that you have a different image file. Can you check that your `graphics/terminal_17x23.png` exactly matches the one in this repo? https://github.com/cxong/cdogs-sdl/blob/master/graphics/terminal_17x23.png

**Comment by cxong** [comment]
The problem with table_plastic is there though - it's because the image is grayscale mode. Changing it to RGB mode should fix it.

**Comment by chack05** [comment]
@cxong It's the same image. I think it might be a similar problem: According to Windows it has 4 bit colour depth. All other "4 bit" colour depth images with totally black parts in it (I observed the animated trees and the radio images) seem to show the same problem.

Some of those image also have thumbnails with a black background but if I load and save with Gimp that goes away. It doesn't fix the problem in-game, though, so I assume the game or some libpng/SDL version just doesn't like colour indexing. Now, if I overwrite the image to 32 bit depth manually it seems to fix the problem.

**Comment by cxong** [comment]
![table](https://user-images.githubusercontent.com/1083215/97854044-0a741880-1d4d-11eb-811a-4d526cddb99e.gif)
fixed table

**Comment by cxong** [comment]
I think this is an SDL library bug, or whatever version of libpng it is using. Tested with newer versions of SDL on windows and don't see this problem anymore.
