### ISSUE TITLE
Build errors: performing pointer subtraction with a null pointer has undefined behavior

### ISSUE THREAD

**Issue by rootkea** [cxong/cdogs-sdl#732]
Hello!

On latest git master, build fails with `clang 13.0.0-2` and `CFLAGS=-Wall -g -O0`.
```
In file included from src/cdogsed/nk_window.c:47:
src/nuklear/nuklear.h:8770:38: error: performing pointer subtraction with a null pointer has undefined behavior [-Werror,-Wnull-pointer-subtraction]
    NK_STORAGE const nk_size align = NK_ALIGNOF(struct nk_command);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/nuklear/nuklear.h:5680:67: note: expanded from macro 'NK_ALIGNOF'
#define NK_ALIGNOF(t) ((char*)(&((struct {char c; t _h;}*)0)->_h) - (char*)0)
                                                                  ^ ~~~~~~~~
```

Thanks!

**Comment by cxong** [comment]
Upstream open issue: https://github.com/Immediate-Mode-UI/Nuklear/issues/94
In the meantime you should ignore the warning

**Comment by cxong** [comment]
Fixed in bc18f798271f1422f34349f2609b1180b4e674cc

**Comment by rootkea** [comment]
Ah, I am still seeing these build errors.

I think imho we should leave this issue open till the Nuklear upstream fixes it.


Also, I'm not sure but it seems that https://github.com/Immediate-Mode-UI/Nuklear/pull/309 has fixed the issue in upstream? If yes then maybe time to bump Nuklear version?

**Comment by rootkea** [comment]
```
$ echo $CC $CXX
clang clang++
$ clang --version
Ubuntu clang version 13.0.0-2
...
$ echo $CFLAGS $CXXFLAGS $LDFLAGS 

$ cmake -Wdev -Wdeprecated --check-system-vars --clean-first -GNinja -D CMAKE_BUILD_TYPE=Debug .
$ ninja
```
I even tried reverting https://github.com/cxong/cdogs-sdl/commit/f773eb1daab1db3073767c74ae932f3d603576b7 but still seeing these errors...
